modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/GenerationsMod/Generations-Structures"
license = "Insert License Here"

[[mods]]
modId = "generations_structures"
version = "${version}"
displayName = "Generations Structures"
authors = "J.T. McQuigg (JT122406)"
description = '''
'''
#logoFile = ""

[[dependencies.generations_structures]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId = "generations_core"
    mandatory = true
    versionRange = "[2.1-Alpha-SNAPSHOT]"
    ordering = "BEFORE"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId = "yungsapi"
    mandatory = true
    versionRange = "[1.20-Forge-4.0,)"
    ordering = "BEFORE"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId = "biomesoplenty"
    mandatory = false
    versionRange = "[18.0.0.592,)"
    ordering = "BEFORE"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId = "byg"
    mandatory = false
    versionRange = "[4.0.0.2,)"
    ordering = "BEFORE"
    side = "BOTH"
