modLoader = "javafml"
loaderVersion = "[47,)"
license="GNU GPL 3.0"
issueTrackerURL = "https://github.com/GenerationsMod/Generations-Structures"

[[mods]]
modId = "generations_structures"
version = "${version}"
displayName = "Generations Structures"
authors = "J.T. McQuigg (JT122406)"
credits = "C. Inglis, Strwbry_Moon, CyborgPixel"
description = '''
Adds structures for the Generations Mod Family
'''
#logoFile = ""

[[dependencies.generations_structures]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.100,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId = "generations_core"
    mandatory = true
    versionRange="*"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId = "biomesoplenty"
    mandatory = false
    versionRange = "[18.0.0.592,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.generations_structures]]
    modId="cobblemon"
    mandatory = true
    versionRange = "1.4.0+1.20.1"
    ordering = "AFTER"
    side = "BOTH"